FROM php:8.2-cli


RUN apt-get update && apt-get install -y git unzip libpq-dev libcurl4-openssl-dev \
    && docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . .

RUN composer install

CMD ["php", "bot/start.php"]