version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: pg-bot
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - botnet

  discord:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: discord
    restart: always
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - botnet

volumes:
  pgdata:

networks:
  botnet:
