version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    networks:
      - api-networks
  postgres: 
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5441:5432"
    volumes:
      - api_postgres:/var/lib/postgresql/data
    networks:
      - api-networks
volumes:
  api_postgres:
networks:
  api-networks:
    driver: bridge