version: "3.8"

services:
  postgres:
    container_name: post
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    container_name: web
    build:
      context: .         
      dockerfile: web/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:80"
    depends_on:
      - postgres

  bot:
    container_name: bot
    build:
      context: .         
      dockerfile: bot/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres

volumes:
  pgdata:
