version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: pg-bot
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  discord-bot:
    build: .
    container_name: discord-bot
    restart: always
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app
    command: php bot.php

volumes:
  pgdata:
